use sdkwork_rpc_core::{SdkworkRpcMethod, SdkworkRpcServiceManifest};

pub fn commerce_app_rpc_service_manifests() -> Vec<SdkworkRpcServiceManifest> {
    vec![
        SdkworkRpcServiceManifest::new(
            "sdkwork.commerce.app.v3",
            "WalletService",
            "app",
            "commerce",
            vec![
                SdkworkRpcMethod::new(
                    "RetrieveWalletOverview",
                    "wallet.overview.retrieve",
                    "dual_token",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListWalletAccounts",
                    "wallet.accounts.list",
                    "dual_token",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListWalletLedgerEntries",
                    "wallet.ledgerEntries.list",
                    "dual_token",
                    false,
                ),
            ],
        ),
        SdkworkRpcServiceManifest::new(
            "sdkwork.commerce.app.v3",
            "CheckoutService",
            "app",
            "commerce",
            vec![
                SdkworkRpcMethod::new(
                    "CreateCheckoutSession",
                    "checkout.sessions.create",
                    "dual_token",
                    true,
                ),
                SdkworkRpcMethod::new(
                    "RetrieveCheckoutSession",
                    "checkout.sessions.retrieve",
                    "dual_token",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "CreateCheckoutQuote",
                    "checkout.sessions.quotes.create",
                    "dual_token",
                    true,
                ),
                SdkworkRpcMethod::new(
                    "CreateCheckoutOrder",
                    "checkout.sessions.orders.create",
                    "dual_token",
                    true,
                ),
            ],
        ),
    ]
}

pub fn commerce_backend_rpc_service_manifests() -> Vec<SdkworkRpcServiceManifest> {
    vec![
        SdkworkRpcServiceManifest::new(
            "sdkwork.commerce.backend.v3",
            "PaymentAdminService",
            "backend",
            "commerce",
            vec![
                SdkworkRpcMethod::new(
                    "ListPaymentProviderAccounts",
                    "payments.providerAccounts.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "CreatePaymentProviderAccount",
                    "payments.providerAccounts.create",
                    "backend_admin",
                    true,
                ),
                SdkworkRpcMethod::new(
                    "ListPaymentMethods",
                    "payments.methods.management.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListPaymentChannels",
                    "payments.channels.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListPaymentIntents",
                    "payments.intents.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListPaymentAttempts",
                    "payments.attempts.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListPaymentReconciliationRuns",
                    "payments.reconciliationRuns.list",
                    "backend_admin",
                    false,
                ),
            ],
        ),
        SdkworkRpcServiceManifest::new(
            "sdkwork.commerce.backend.v3",
            "CommerceReportService",
            "backend",
            "commerce",
            vec![
                SdkworkRpcMethod::new(
                    "ListUsageStatements",
                    "commerceReports.usageStatements.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "RetrievePaymentReconciliation",
                    "commerceReports.paymentReconciliation.retrieve",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListOrderRevenue",
                    "commerceReports.orderRevenue.list",
                    "backend_admin",
                    false,
                ),
                SdkworkRpcMethod::new(
                    "ListRefundReports",
                    "commerceReports.refunds.list",
                    "backend_admin",
                    false,
                ),
            ],
        ),
    ]
}

pub fn all_commerce_rpc_service_manifests() -> Vec<SdkworkRpcServiceManifest> {
    let mut manifests = commerce_app_rpc_service_manifests();
    manifests.extend(commerce_backend_rpc_service_manifests());
    manifests
}
